const WORLD_CUP_TEAM_NAME_ALIASES = {
  "alzir": "Algeria",
  "algeria": "Algeria",
  "argentina": "Argentina",
  "australija": "Australia",
  "australia": "Australia",
  "austrija": "Austria",
  "austria": "Austria",
  "belgija": "Belgium",
  "belgium": "Belgium",
  "bosna i hercegovina": "Bosnia & Herzegovina",
  "bosnia and herzegovina": "Bosnia & Herzegovina",
  "bosnia & herzegovina": "Bosnia & Herzegovina",
  "brazil": "Brazil",
  "kamerun": "Cameroon",
  "cameroon": "Cameroon",
  "kanada": "Canada",
  "canada": "Canada",
  "zelenortska ostrva": "Cape Verde",
  "cape verde": "Cape Verde",
  "cile": "Chile",
  "chile": "Chile",
  "kina": "China",
  "china": "China",
  "kolumbija": "Colombia",
  "colombia": "Colombia",
  "kostarika": "Costa Rica",
  "costa rica": "Costa Rica",
  "hrvatska": "Croatia",
  "croatia": "Croatia",
  "kurasao": "Curacao",
  "curacao": "Curacao",
  "ceska": "Czech Republic",
  "ceska republika": "Czech Republic",
  "czech republic": "Czech Republic",
  "danska": "Denmark",
  "denmark": "Denmark",
  "demokratska republika kongo": "DR Congo",
  "dr kongo": "DR Congo",
  "d r kongo": "DR Congo",
  "d.r. kongo": "DR Congo",
  "dr congo": "DR Congo",
  "d r congo": "DR Congo",
  "d.r. congo": "DR Congo",
  "ekvador": "Ecuador",
  "ecuador": "Ecuador",
  "egipat": "Egypt",
  "egypt": "Egypt",
  "engleska": "England",
  "england": "England",
  "francuska": "France",
  "france": "France",
  "nemacka": "Germany",
  "germany": "Germany",
  "ghana": "Ghana",
  "gana": "Ghana",
  "grcka": "Greece",
  "greece": "Greece",
  "madjarska": "Hungary",
  "mađarska": "Hungary",
  "hungary": "Hungary",
  "haiti": "Haiti",
  "iran": "Iran",
  "irak": "Iraq",
  "iraq": "Iraq",
  "irska": "Ireland",
  "ireland": "Ireland",
  "italija": "Italy",
  "italy": "Italy",
  "obala slonovace": "Ivory Coast",
  "ivory coast": "Ivory Coast",
  "japan": "Japan",
  "jordan": "Jordan",
  "republika koreja": "South Korea",
  "juzna koreja": "South Korea",
  "južna koreja": "South Korea",
  "korea republic": "South Korea",
  "south korea": "South Korea",
  "meksiko": "Mexico",
  "mexico": "Mexico",
  "maroko": "Morocco",
  "morocco": "Morocco",
  "holandija": "Netherlands",
  "nizozemska": "Netherlands",
  "netherlands": "Netherlands",
  "novi zeland": "New Zealand",
  "new zealand": "New Zealand",
  "nigerija": "Nigeria",
  "nigeria": "Nigeria",
  "norveska": "Norway",
  "norveška": "Norway",
  "norway": "Norway",
  "panama": "Panama",
  "paraguay": "Paraguay",
  "peru": "Peru",
  "poljska": "Poland",
  "poland": "Poland",
  "portugal": "Portugal",
  "qatar": "Qatar",
  "katar": "Qatar",
  "rumunija": "Romania",
  "romania": "Romania",
  "saudijska arabija": "Saudi Arabia",
  "saudi arabia": "Saudi Arabia",
  "skotska": "Scotland",
  "škotska": "Scotland",
  "scotland": "Scotland",
  "senegal": "Senegal",
  "srbija": "Serbia",
  "serbia": "Serbia",
  "slovacka": "Slovakia",
  "slovačka": "Slovakia",
  "slovakia": "Slovakia",
  "slovenija": "Slovenia",
  "slovenia": "Slovenia",
  "juzna afrika": "South Africa",
  "južna afrika": "South Africa",
  "south africa": "South Africa",
  "spanija": "Spain",
  "španija": "Spain",
  "spain": "Spain",
  "svedska": "Sweden",
  "švedska": "Sweden",
  "sweden": "Sweden",
  "svajcarska": "Switzerland",
  "švajcarska": "Switzerland",
  "switzerland": "Switzerland",
  "tunis": "Tunisia",
  "tunisia": "Tunisia",
  "turska": "Turkey",
  "turkey": "Turkey",
  "ukrajina": "Ukraine",
  "ukraine": "Ukraine",
  "uruguay": "Uruguay",
  "urugvaj": "Uruguay",
  "sjedinjene americke drzave": "USA",
  "sjedinjene americke države": "USA",
  "sad": "USA",
  "usa": "USA",
  "united states": "USA",
  "uzbekistan": "Uzbekistan",
  "venecuela": "Venezuela",
  "venezuela": "Venezuela",
  "vels": "Wales",
  "wales": "Wales"
};

export function getWorldCupTeamAlias(name) {
  const direct = WORLD_CUP_TEAM_NAME_ALIASES[normalizeTeamName(name)];
  if (direct) return direct;
  return "";
}

export function normalizeTeamName(value) {
  return String(value || "")
    .replace(/[\u00a0\u2007\u2008\u2009\u202f\u205f\u3000]/g, " ")
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/\b(fc|national team|women)\b/gi, "")
    .replace(/\s+/g, " ")
    .trim()
    .toLowerCase();
}
