"""Regenerate js/handball_player_teams.js from the roster spreadsheet.

    python build_handball_teams.py ["handball roster.xlsx"]

The sheet has no header: column A is the player ("First Last"), column B the
team. Names are ASCII-folded on the way out so the JS file stays pure ASCII
(see the encoding note in CLAUDE.md); the page folds the SuperSport side the
same way before comparing, and ignores word order, so "Aleks Vlah" here
matches SuperSport's "Vlah Aleks".

Team names only need to be close to SuperSport's spelling - the page matches
them loosely ("Kielce" covers "Vive Kielce"). TEAM_RENAMES is for the ones
that share no words with it.
"""

import json
import re
import sys
import unicodedata
from pathlib import Path

import openpyxl

ROOT = Path(__file__).resolve().parent
OUTPUT = ROOT / "js" / "handball_player_teams.js"

# Roster spelling -> a spelling the page can match against SuperSport's.
TEAM_RENAMES = {
    "Dinamo Bucarest": "Dinamo Bukurest",
}

# Letters NFD does not decompose into base + accent.
SPECIAL_LETTERS = {
    "þ": "th", "Þ": "Th", "ð": "d", "Ð": "D", "æ": "ae", "Æ": "Ae",
    "ø": "o", "Ø": "O", "ł": "l", "Ł": "L", "ß": "ss", "đ": "dj", "Đ": "Dj",
}

HEADER = '''/**
 * Which team a handball player plays for, as `[player, team]` tuples.
 *
 * GENERATED by build_handball_teams.py from "handball roster.xlsx" - edit the
 * spreadsheet and re-run the script rather than editing this file by hand.
 *
 * SuperSport's player lines carry no team ("zbroj golova Vlah Aleks (5.5)"),
 * so the Rukomet page looks the player up here among the two teams of that
 * fixture only - which is what makes loose matching safe:
 * - word order and diacritics are ignored ("Aleks Vlah" = "Vlah Aleks");
 * - a name may be missing words ("Gisli Kristjansson" matches SuperSport's
 *   "Kristjansson Gisli Thorgeir") as long as it is unambiguous;
 * - teams match when every word of the shorter name is in the longer one
 *   ("Kielce" covers "Vive Kielce").
 * Links learned from "+ Dom" / "+ Gost" clicks are kept in localStorage and
 * win over this table.
 */
export const HANDBALL_PLAYER_TEAMS = [
'''


def to_ascii(value):
    text = str(value).strip()
    for letter, replacement in SPECIAL_LETTERS.items():
        text = text.replace(letter, replacement)
    text = unicodedata.normalize("NFD", text)
    text = "".join(ch for ch in text if not unicodedata.combining(ch))
    return re.sub(r"\s+", " ", text)


def main():
    source = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "handball roster.xlsx"
    sheet = openpyxl.load_workbook(source, read_only=True).worksheets[0]

    entries = {}
    for row in sheet.iter_rows(values_only=True):
        if len(row) < 2 or not row[0] or not row[1]:
            continue
        team = str(row[1]).strip()
        player = to_ascii(row[0])
        team = to_ascii(TEAM_RENAMES.get(team, team))
        key = " ".join(sorted(player.lower().split()))
        if key in entries and entries[key][1] != team:
            print(f"warning: {player} listed for {entries[key][1]} and {team}; keeping {team}")
        entries[key] = (player, team)

    rows = sorted(entries.values(), key=lambda e: (e[1], e[0]))
    body = "".join(f"  [{json.dumps(p)}, {json.dumps(t)}],\n" for p, t in rows)
    OUTPUT.write_text(HEADER + body + "];\n", encoding="utf-8", newline="\n")

    teams = sorted({t for _, t in rows})
    print(f"{len(rows)} players, {len(teams)} teams -> {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
