[build]
  publish = "."

[[redirects]]
  from = "/sb-api/*"
  to = "https://production-superbet-offer-rs.freetls.fastly.net/sb-rs/api/v2/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/fpl-api/*"
  to = "https://fantasy.premierleague.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/mx-api/*"
  to = "https://www.merkurxtip.rs/restapi/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/bb-api/*"
  to = "https://sports-sm-distribution-api.de-2.nsoftcdn.com/api/v1/:splat"
  status = 200
  force = true
